extends Node3D
## RunnerTrack
##
## The scrolling world for the Infinite Runner. The player never actually moves
## down the track — the track moves past it — so "infinite" is just a handful of
## ground tiles and a stream of obstacles recycled toward the camera. This node
## owns all of that: it builds the graveyard-corridor tiles, spawns/recycles
## obstacles by distance, and reports collisions against the player it was handed.
##
## runner.gd drives it: each frame it calls [method scroll] with the current run
## speed; the track moves everything +Z, recycles what passes behind, spawns new
## hazards ahead, and emits [signal obstacle_hit] when the player fails to avoid
## one. runner.gd owns the chase/tension; this owns the world.
class_name RunnerTrack

## Emitted once when the player strikes an obstacle they didn't avoid, with the
## obstacle's [enum ObstacleType].
signal obstacle_hit(type: int)
## Emitted once when the player cleanly clears an obstacle (for a small reward).
signal obstacle_cleared(type: int)

enum ObstacleType { JUMP, DUCK, SIDE }

const TRACK_WIDTH: float = 8.0
const TILE_LEN: float = 16.0
const TILE_COUNT: int = 9
## Anything that scrolls past this Z (behind the camera) is recycled/freed.
const RECYCLE_Z: float = 24.0
## Obstacles are born this far ahead (down -Z) and scroll toward the player.
const SPAWN_Z: float = -140.0
## Player's forgiveness half-width for side-block collisions (metres).
const PLAYER_HALF_W: float = 0.55
## A leap clears a barrier if the player was airborne at any point while the
## barrier was inside this Z band around the player plane — a bit before it
## arrives (JUMP_CLEAR_LEAD) through a bit past it (JUMP_CLEAR_TRAIL). This turns
## a single-frame check into a forgiving window, so a jump that starts a touch
## early or late still carries you OVER the hurdle instead of landing on it.
const JUMP_CLEAR_LEAD: float = 2.4
const JUMP_CLEAR_TRAIL: float = 0.8

## Distance (m) between consecutive obstacles; scaled by difficulty via
## [member spacing_scale] (smaller = denser = harder).
const SPACING_MIN: float = 22.0
const SPACING_MAX: float = 34.0

## Props are textured from assets/textures/runner/ (generated by gen_props.py
## there; packing: RGB=albedo A=bump / RGB=normal A=rough). Materials are built
## once per texture+scale+tint in [method _mat] and shared; tints multiply the
## baked albedo, so Color.WHITE shows the texture as authored.
const TEX_DIR: String = "res://assets/textures/runner/"
## Ground/rail textures run the full 16 m tile, so their triplanar scale must
## put an INTEGER number of repeats on TILE_LEN or the texture jumps at every
## tile joint: 6/16 for the path, 10/16 for the rubble walls.
const GROUND_UV: float = 0.375
const RAIL_UV: float = 0.625
## Dark red ember tint under the hazards' glow (multiplies the rubble texture).
const HAZARD_TINT: Color = Color(0.55, 0.24, 0.2)
const HAZARD_EMIT: Color = Color(0.7, 0.08, 0.05)
## Crypt doorway: a lightless slab so the opening reads as a black void.
const DOOR_COLOR: Color = Color(0.03, 0.028, 0.035)
## Low ground fog: a faint, near-transparent pale slab that drifts past at ankle
## height so the corridor feels like it's steaming.
const MIST_COLOR: Color = Color(0.5, 0.55, 0.62, 0.04)

var spacing_scale: float = 1.0

var _player: RunnerPlayer
var _tiles: Array[Node3D] = []
# Each entry: { node:Node3D, type:int, x_min:float, x_max:float, resolved:bool }
var _obstacles: Array[Dictionary] = []
var _dist_since_spawn: float = 0.0
var _next_spacing: float = 26.0
var _rng := RandomNumberGenerator.new()
# Shared prop materials, keyed "texture|uv_scale|tint" (see _mat). Hazards
# duplicate theirs because _mark_struck mutates emission per instance.
var _mat_cache: Dictionary = {}


## Called by runner.gd before play to hand over the player it should test hits
## against and build the static scenery (so the intro countdown reveals a dressed
## track). Safe to call again to reset.
func setup(player: RunnerPlayer) -> void:
	_player = player
	if _tiles.is_empty():
		_build_tiles()


func start() -> void:
	_rng.randomize()
	for entry in _obstacles:
		var node: Node3D = entry["node"]
		if is_instance_valid(node):
			node.queue_free()
	_obstacles.clear()
	_dist_since_spawn = 0.0
	_next_spacing = _rng.randf_range(SPACING_MIN, SPACING_MAX) * spacing_scale


## Advances the world by [param speed] m/s for [param delta] seconds: scrolls
## tiles + obstacles toward the camera, recycles/frees what passes behind, spawns
## fresh hazards ahead, and resolves collisions as obstacles cross the player.
## Pass [param spawn] false (used during the pre-chase briefing) to scroll only
## the scenery — the world still rushes past so the player can warm up marching,
## but no hazards appear.
func scroll(delta: float, speed: float, spawn: bool = true) -> void:
	var dz: float = speed * delta
	for tile in _tiles:
		tile.position.z += dz
		if tile.position.z > RECYCLE_Z:
			tile.position.z -= TILE_COUNT * TILE_LEN
	if spawn:
		_scroll_obstacles(dz)
		_spawn_by_distance(dz)


func _scroll_obstacles(dz: float) -> void:
	var survivors: Array[Dictionary] = []
	for entry in _obstacles:
		var node: Node3D = entry["node"]
		if not is_instance_valid(node):
			continue
		node.position.z += dz
		var z: float = node.position.z
		# JUMP barriers clear over a Z band: latch the moment the player is
		# airborne over the approaching hurdle, then settle the outcome once the
		# hurdle has passed the trailing plane. Other hazards resolve instantly
		# at the player plane.
		if not entry["resolved"] and entry["type"] == ObstacleType.JUMP:
			if z >= -JUMP_CLEAR_LEAD and not entry["cleared"] and _player.is_clearing():
				entry["cleared"] = true
			if z >= JUMP_CLEAR_TRAIL:
				entry["resolved"] = true
				_resolve(entry)
		elif not entry["resolved"] and z >= 0.0:
			entry["resolved"] = true
			_resolve(entry)
		if node.position.z > RECYCLE_Z:
			node.queue_free()
		else:
			survivors.append(entry)
	_obstacles = survivors


func _resolve(entry: Dictionary) -> void:
	var type: int = entry["type"]
	var hit: bool = false
	match type:
		ObstacleType.JUMP:
			hit = not entry["cleared"]  # latched across the clearance band
		ObstacleType.DUCK:
			hit = not _player.is_sliding()
		ObstacleType.SIDE:
			var px: float = _player.center_x()
			hit = px > entry["x_min"] - PLAYER_HALF_W and px < entry["x_max"] + PLAYER_HALF_W
	if hit:
		obstacle_hit.emit(type)
		_mark_struck(entry["node"])
	else:
		obstacle_cleared.emit(type)


func _spawn_by_distance(dz: float) -> void:
	_dist_since_spawn += dz
	if _dist_since_spawn < _next_spacing:
		return
	_dist_since_spawn = 0.0
	_next_spacing = _rng.randf_range(SPACING_MIN, SPACING_MAX) * spacing_scale
	_spawn_obstacle()


func _spawn_obstacle() -> void:
	var type: int = [ObstacleType.JUMP, ObstacleType.DUCK,
			ObstacleType.SIDE, ObstacleType.SIDE][_rng.randi() % 4]
	var node := Node3D.new()
	var x_min: float = -TRACK_WIDTH
	var x_max: float = TRACK_WIDTH
	match type:
		ObstacleType.JUMP:
			node.add_child(_hazard_box(Vector3(TRACK_WIDTH, 0.7, 0.6), Vector3(0, 0.35, 0)))
			# chunks along the top so the barrier reads as collapsed masonry
			node.add_child(_hazard_box(Vector3(0.9, 0.34, 0.5),
					Vector3(-TRACK_WIDTH * 0.28, 0.85, 0.0)))
			node.add_child(_hazard_box(Vector3(0.7, 0.26, 0.45),
					Vector3(TRACK_WIDTH * 0.19, 0.82, 0.06)))
		ObstacleType.DUCK:
			node.add_child(_hazard_box(Vector3(TRACK_WIDTH, 0.45, 0.45), Vector3(0, 2.05, 0)))
			# gallows-like wooden posts so the overhead bar reads as a barrier
			# to duck under
			node.add_child(_prop_box(Vector3(0.22, 2.1, 0.22),
					Vector3(TRACK_WIDTH * 0.5 - 0.11, 1.05, 0), _mat("wood", 1.0)))
			node.add_child(_prop_box(Vector3(0.22, 2.1, 0.22),
					Vector3(-TRACK_WIDTH * 0.5 + 0.11, 1.05, 0), _mat("wood", 1.0)))
		ObstacleType.SIDE:
			var left: bool = _rng.randf() < 0.5
			var cx: float = -TRACK_WIDTH * 0.25 if left else TRACK_WIDTH * 0.25
			node.add_child(_hazard_box(Vector3(TRACK_WIDTH * 0.5, 2.3, 1.0),
					Vector3(cx, 1.15, 0)))
			x_min = cx - TRACK_WIDTH * 0.25
			x_max = cx + TRACK_WIDTH * 0.25
	node.position = Vector3(0, 0, SPAWN_Z)
	add_child(node)
	_obstacles.append({"node": node, "type": type,
			"x_min": x_min, "x_max": x_max, "resolved": false, "cleared": false})


## Returns the coaching cue for the nearest un-resolved hazard bearing down on the
## player, or an empty Dictionary. { action:String, color_danger:bool }.
func nearest_prompt() -> Dictionary:
	var best: Dictionary = {}
	var best_z: float = -1000.0
	for entry in _obstacles:
		if entry["resolved"]:
			continue
		var z: float = (entry["node"] as Node3D).position.z
		if z < -18.0 or z > -2.0:
			continue
		if z > best_z:  # nearest to the player (largest, least-negative z)
			best_z = z
			best = entry
	if best.is_empty():
		return {}
	match int(best["type"]):
		ObstacleType.JUMP:
			return {"action": "JUMP!"}
		ObstacleType.DUCK:
			return {"action": "DUCK!"}
		_:
			# dodge to the OPEN side (away from the block's centre)
			var block_left: bool = (best["x_min"] + best["x_max"]) * 0.5 < 0.0
			return {"action": "DODGE RIGHT →" if block_left else "← DODGE LEFT"}


# --- construction ------------------------------------------------------------

func _build_tiles() -> void:
	for i in TILE_COUNT:
		var tile := _make_tile(i)
		add_child(tile)
		_tiles.append(tile)


## One ground segment: the dirt path, rubble side walls, a drifting ribbon of
## ground fog, and a graveyard's worth of scenery beyond the walls so the eye
## reads speed and the corridor feels genuinely grim. The scenery is seeded off
## the tile index so it's varied and non-repeating but stable per tile.
func _make_tile(index: int) -> Node3D:
	var tile := Node3D.new()
	tile.position.z = TILE_LEN * 0.5 - index * TILE_LEN  # tile 0 just ahead
	# The textures are authored bright enough to inspect; the midnight mood
	# comes from tinting them down here so the corridor stays near-black.
	tile.add_child(_prop_box(Vector3(TRACK_WIDTH, 0.2, TILE_LEN),
			Vector3(0, -0.1, 0), _mat("dirt", GROUND_UV, Color(0.5, 0.47, 0.46))))
	# a dark verge under the scenery on each side, so gravestones and crypts
	# stand on ground instead of floating over the void
	var rail_x: float = TRACK_WIDTH * 0.5 + 0.2
	for side in [1.0, -1.0]:
		tile.add_child(_prop_box(Vector3(8.0, 0.16, TILE_LEN),
				Vector3((rail_x + 4.0) * side, -0.08, 0),
				_mat("dirt", GROUND_UV, Color(0.3, 0.28, 0.28))))
	# low rubble walls fencing the corridor
	tile.add_child(_prop_box(Vector3(0.3, 0.8, TILE_LEN),
			Vector3(rail_x, 0.4, 0), _mat("rubble", RAIL_UV, Color(0.55, 0.53, 0.52))))
	tile.add_child(_prop_box(Vector3(0.3, 0.8, TILE_LEN),
			Vector3(-rail_x, 0.4, 0), _mat("rubble", RAIL_UV, Color(0.55, 0.53, 0.52))))
	# A faint sheet of fog hovering over the path so it steams.
	tile.add_child(_mist_slab(Vector2(TRACK_WIDTH - 0.6, TILE_LEN),
			Vector3(0, 0.22, 0)))
	# Scenery beyond each rail, one prop per side, its kind chosen from the tile
	# index so the corridor never reads as an obvious loop.
	tile.add_child(_scenery(index, 1.0, rail_x))
	tile.add_child(_scenery(index + 1, -1.0, rail_x))
	return tile


## Builds one piece of roadside scenery on the [param side] (+1 right / -1 left),
## just beyond the rail. The kind (gravestone, pillar, dead tree, crypt, fence)
## and depth are picked deterministically from [param seed] so the world varies
## without an RNG and stays identical every time a tile recycles.
func _scenery(seed: int, side: float, rail_x: float) -> Node3D:
	var holder := Node3D.new()
	# keep even the near props clear of the wall line, or from the low chase
	# camera they read as growths on top of the wall itself
	var near_x: float = (rail_x + 1.6) * side
	var far_x: float = (rail_x + 3.2) * side
	var depth: float = float((seed * 37) % 12) - 6.0  # -6..+5 along the tile
	# Props are modelled at true scale but viewed from a camera ~10 m behind
	# the player through fog, which shrinks them to clutter — so scenery is
	# built oversized to keep silhouette presence from the chase camera.
	var prop: Node3D
	var grow: float
	match seed % 5:
		0:
			prop = _gravestone(seed, side, Vector3(near_x, 0, depth))
			grow = 1.7
		1:
			prop = _dead_tree(seed, side, Vector3(far_x, 0, depth))
			grow = 1.6
		2:
			prop = _broken_pillar(seed, side, Vector3(near_x, 0, depth))
			grow = 1.7
		3:
			prop = _crypt(side, Vector3(far_x + 1.6 * side, 0, depth))
			grow = 1.45
		_:
			prop = _fence(seed, side, Vector3(near_x, 0, depth))
			grow = 1.5
	# scale about the prop's own ground point, not the tile origin
	prop.scale = Vector3.ONE * grow
	holder.add_child(prop)
	return holder


## Leaning headstone: plinth, slab, and a half-round cap, all weathered
## limestone. The whole marker leans off vertical like old graves do.
func _gravestone(seed: int, side: float, pos: Vector3) -> Node3D:
	var g := Node3D.new()
	g.position = pos
	g.rotation.z = (0.08 + 0.1 * _hash01(seed, 3)) * side
	var stone := _mat("grave", 0.9)
	g.add_child(_prop_box(Vector3(1.0, 0.18, 0.55), Vector3(0, 0.09, 0), stone))
	g.add_child(_prop_box(Vector3(0.78, 0.85, 0.16), Vector3(0, 0.6, 0), stone))
	var cap := _prop_cyl(0.39, 0.39, 0.16, Vector3(0, 1.02, 0), stone, 12)
	cap.rotation.x = PI * 0.5  # cylinder axis along the slab's thickness
	g.add_child(cap)
	return g


## Dead tree: flared roots, tapered leaning trunk, and asymmetric bare branches
## (heights/angles differ per side so the silhouette never reads as a cross,
## and never as the same tree twice).
func _dead_tree(seed: int, side: float, pos: Vector3) -> Node3D:
	var t := Node3D.new()
	t.position = pos
	var bark := _mat("bark", 0.8)
	t.add_child(_prop_cyl(0.34, 0.19, 0.55, Vector3(0, 0.27, 0), bark, 8))
	var trunk := _prop_cyl(0.19, 0.06, 3.0, Vector3(0, 1.95, 0), bark, 8)
	trunk.rotation.z = (0.04 + 0.06 * _hash01(seed, 5)) * side
	t.add_child(trunk)
	# main limb reaching up-and-out, a lower stub the other way, a snapped twig
	t.add_child(_branch(bark, 2.35, (0.9 + 0.3 * _hash01(seed, 7)) * side, 1.25, 0.07))
	t.add_child(_branch(bark, 1.65, -0.65 * side, 0.8, 0.055))
	t.add_child(_branch(bark, 2.85, 1.35 * side, 0.45, 0.045))
	return t


## One bare branch: a tapered cylinder whose base sits on the trunk at height
## [param h], tipped [param ang] radians off vertical.
func _branch(mat: StandardMaterial3D, h: float, ang: float, length: float,
		radius: float) -> MeshInstance3D:
	var b := _prop_cyl(radius, radius * 0.35, length, Vector3.ZERO, mat, 6)
	b.rotation.z = ang
	# rotating +Y by ang about Z sends the tip toward (-sin, cos); center the
	# branch half a length along that direction from its base on the trunk
	b.position = Vector3(-sin(ang) * length * 0.5, h + cos(ang) * length * 0.5, 0)
	return b


## Broken memorial pillar: square plinth, leaning fluted shaft with a jagged
## offset break at the top, and a toppled drum sunk beside it.
func _broken_pillar(seed: int, side: float, pos: Vector3) -> Node3D:
	var p := Node3D.new()
	p.position = pos
	var stone := _mat("grave", 0.9)
	p.add_child(_prop_box(Vector3(0.64, 0.16, 0.64), Vector3(0, 0.08, 0), stone))
	var shaft := _prop_cyl(0.18, 0.15, 1.3, Vector3(0, 0.81, 0), stone, 9)
	shaft.rotation.z = -0.05 * side
	p.add_child(shaft)
	var brk := _prop_cyl(0.15, 0.09, 0.26, Vector3(0.05 * side, 1.5, 0.03), stone, 9)
	brk.rotation.z = (0.25 + 0.2 * _hash01(seed, 11)) * side
	p.add_child(brk)
	var drum := _prop_cyl(0.15, 0.15, 0.5, Vector3(0.6 * side, 0.13, 0.35), stone, 9)
	drum.rotation.x = PI * 0.5
	drum.rotation.y = 0.4 * side
	p.add_child(drum)
	return p


## Hulking mausoleum: block-masonry body, gabled rubble roof with its gable end
## facing the track, a black doorway framed by proud limestone jambs and a
## lintel, and a step out front. [param side] aims the entrance at the runner.
func _crypt(side: float, pos: Vector3) -> Node3D:
	var c := Node3D.new()
	c.position = pos
	var wall := _mat("crypt", 0.55)
	var stone := _mat("grave", 0.9)
	var front: float = -1.2 * side  # body face closest to the track
	c.add_child(_prop_box(Vector3(2.4, 1.8, 2.2), Vector3(0, 0.9, 0), wall))
	var roof := _prop_prism(Vector3(2.6, 0.75, 2.7), Vector3(0, 2.17, 0),
			_mat("rubble", RAIL_UV))
	roof.rotation.y = PI * 0.5  # ridge along X: gable end faces the track
	c.add_child(roof)
	c.add_child(_prop_box(Vector3(0.06, 1.15, 0.62),
			Vector3(front - 0.02 * side, 0.58, 0), _mat_flat(DOOR_COLOR)))
	c.add_child(_prop_box(Vector3(0.16, 0.2, 0.95),
			Vector3(front - 0.04 * side, 1.26, 0), stone))
	c.add_child(_prop_box(Vector3(0.16, 1.25, 0.16),
			Vector3(front - 0.04 * side, 0.62, 0.44), stone))
	c.add_child(_prop_box(Vector3(0.16, 1.25, 0.16),
			Vector3(front - 0.04 * side, 0.62, -0.44), stone))
	c.add_child(_prop_box(Vector3(0.5, 0.14, 1.1),
			Vector3(front - 0.35 * side, 0.07, 0), _mat("rubble", RAIL_UV)))
	return c


## Collapsing picket fence: rotten posts at drunken angles with a sagging
## horizontal rail still nailed across them.
func _fence(seed: int, side: float, pos: Vector3) -> Node3D:
	var f := Node3D.new()
	f.position = pos
	var wood := _mat("wood", 1.0)
	for i in 4:
		var h: float = 0.85 - 0.14 * _hash01(seed, i)
		var post := _prop_box(Vector3(0.13, h, 0.13),
				Vector3((i - 1.5) * 0.55 * side, h * 0.5, 0), wood)
		post.rotation.z = (_hash01(seed, i + 20) - 0.5) * 0.3
		post.rotation.x = (_hash01(seed, i + 40) - 0.5) * 0.16
		f.add_child(post)
	var rail := _prop_box(Vector3(1.9, 0.09, 0.06), Vector3(0, 0.52, 0.05), wood)
	rail.rotation.z = (_hash01(seed, 60) - 0.5) * 0.22
	f.add_child(rail)
	return f


# --- prop building blocks ------------------------------------------------------

## Deterministic hash → [0,1), so scenery varies per tile without an RNG and is
## identical every time the tile recycles.
func _hash01(seed: int, salt: int) -> float:
	return float((absi(seed * 73856093 ^ salt * 19349663)) % 1024) / 1024.0


## Returns the shared textured material for [param tex] (a gen_props.py set) at
## triplanar [param uv_scale], tinted by [param tint]. Triplanar mapping is in
## object space, so the texture sticks to props as the track scrolls and no
## per-face UV work is needed on primitive meshes.
func _mat(tex: String, uv_scale: float, tint: Color = Color.WHITE) -> StandardMaterial3D:
	var key := "%s|%.3f|%s" % [tex, uv_scale, tint]
	if _mat_cache.has(key):
		return _mat_cache[key]
	var m := StandardMaterial3D.new()
	m.albedo_color = tint
	var albedo := load(TEX_DIR + tex + "_albedo_bump.png") as Texture2D
	var nr := load(TEX_DIR + tex + "_normal_rough.png") as Texture2D
	if albedo != null:
		m.albedo_texture = albedo
	if nr != null:
		m.normal_enabled = true
		m.normal_texture = nr
		m.roughness_texture = nr
		m.roughness_texture_channel = BaseMaterial3D.TEXTURE_CHANNEL_ALPHA
	m.roughness = 1.0
	m.uv1_triplanar = true
	m.uv1_scale = Vector3.ONE * uv_scale
	_mat_cache[key] = m
	return m


## Shared flat-color material (the crypt's void doorway).
func _mat_flat(color: Color) -> StandardMaterial3D:
	var key := "flat|%s" % color
	if _mat_cache.has(key):
		return _mat_cache[key]
	var m := StandardMaterial3D.new()
	m.albedo_color = color
	m.roughness = 1.0
	_mat_cache[key] = m
	return m


func _prop_box(size: Vector3, pos: Vector3, mat: StandardMaterial3D) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var box := BoxMesh.new()
	box.size = size
	box.material = mat
	mi.mesh = box
	mi.position = pos
	return mi


func _prop_cyl(bottom_r: float, top_r: float, height: float, pos: Vector3,
		mat: StandardMaterial3D, radial: int = 9) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var cyl := CylinderMesh.new()
	cyl.bottom_radius = bottom_r
	cyl.top_radius = top_r
	cyl.height = height
	cyl.radial_segments = radial
	cyl.rings = 1
	cyl.material = mat
	mi.mesh = cyl
	mi.position = pos
	return mi


func _prop_prism(size: Vector3, pos: Vector3, mat: StandardMaterial3D) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var prism := PrismMesh.new()
	prism.size = size
	prism.material = mat
	mi.mesh = prism
	mi.position = pos
	return mi


## A faint, unshaded translucent sheet used for the drifting ground fog. It's a
## flat horizontal plane, NOT a box: a translucent box's vertical end-faces
## render as pale bands slicing across the road at every tile joint, and its
## stacked side-walls wash out the whole corridor (seen in play, 2026-07-17).
## Unshaded so it stays an even haze; never casts shadows.
func _mist_slab(size: Vector2, pos: Vector3) -> MeshInstance3D:
	var mi := MeshInstance3D.new()
	var plane := PlaneMesh.new()
	plane.size = size
	var mat := StandardMaterial3D.new()
	mat.albedo_color = MIST_COLOR
	mat.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
	mat.shading_mode = BaseMaterial3D.SHADING_MODE_UNSHADED
	mat.cull_mode = BaseMaterial3D.CULL_DISABLED
	plane.material = mat
	mi.mesh = plane
	mi.position = pos
	mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	return mi


## An ember-lit masonry block: the shared rubble texture under a dark red tint
## with the gameplay-critical red glow on top. The material is duplicated per
## hazard (sharing the textures) because _mark_struck mutates its emission.
func _hazard_box(size: Vector3, pos: Vector3) -> MeshInstance3D:
	var mat: StandardMaterial3D = _mat("rubble", 0.85, HAZARD_TINT).duplicate()
	mat.emission_enabled = true
	mat.emission = HAZARD_EMIT
	# glow THROUGH the rubble texture (multiply), not over it — the stones read
	# as ember-lit masonry with dark mortar seams instead of a flat red slab
	mat.emission_texture = mat.albedo_texture
	mat.emission_operator = BaseMaterial3D.EMISSION_OP_MULTIPLY
	mat.emission_energy_multiplier = 3.2
	var mi := _prop_box(size, pos, mat)
	mi.set_meta("hazard", true)
	return mi


## Flares a struck hazard's glow so a hit reads as "you clipped it".
func _mark_struck(node: Node3D) -> void:
	for child in node.get_children():
		var mi := child as MeshInstance3D
		if mi != null and mi.has_meta("hazard"):
			var mat: StandardMaterial3D = (mi.mesh as BoxMesh).material
			if mat != null:
				mat.emission_energy_multiplier = 7.0
