extends Node3D
## RunnerZombie
##
## The pursuer. Purely a visual actor: runner.gd owns the chase maths (the "gap")
## and each frame parks this node just behind the player at a distance derived
## from that gap — so the closer the zombie is on the danger meter, the closer and
## larger it actually looms in the frame. This script only loads the model and
## drives its animation.
##
## The model is the bundled zombie GLB (generated by
## assets/models/generated_human/export_zombie_glb.py — a gaunt, green reskin of
## the player rig with hunched shamble / lunge / idle clips). It's parsed at
## runtime via GLTFDocument (like CharacterFactory), so no editor import step is
## needed. Like the player it's turned to run DOWN the track (-Z) so its shamble
## strides in the chase direction instead of moonwalking; the tight over-the-head
## camera keeps it behind you and unseen until it surges onto your back.
class_name RunnerZombie

const MODEL_PATH: String = "res://assets/models/zombie/zombie.glb"
const CLIP_SHAMBLE: String = "shamble"
const CLIP_LUNGE: String = "lunge"
const CLIP_IDLE: String = "idle"
## Shamble playback scales a little with how hard the zombie is gaining, so a
## closing zombie visibly quickens.
const SHAMBLE_MIN: float = 0.9
const SHAMBLE_MAX: float = 1.6

var _character: Node3D
var _anim: AnimationPlayer
var _clips: PackedStringArray
var _lunging: bool = false


func _ready() -> void:
	_spawn()


func _spawn() -> void:
	var doc := GLTFDocument.new()
	var state := GLTFState.new()
	if doc.append_from_file(MODEL_PATH, state) != OK:
		push_warning("RunnerZombie: could not parse %s" % MODEL_PATH)
		return
	_character = doc.generate_scene(state) as Node3D
	if _character == null:
		return
	add_child(_character)
	RigUtils.plant_feet(_character, 0.0, PI)  # authored facing +Z; run toward -Z (down track)
	_apply_glow()
	_anim = _character.find_child("AnimationPlayer", true, false)
	if _anim != null:
		_clips = _anim.get_animation_list()
		RigUtils.loop_clips(_anim, [CLIP_LUNGE])
		var start: String = CLIP_SHAMBLE if _clips.has(CLIP_SHAMBLE) else _clips[0]
		_anim.play(start)


## Makes the zombie read against the dark, foggy track: a faint self-illumination
## tinted to each part's own colour so it approaches like a pale specter, plus
## bright glowing eyes. The GLB's baked materials aren't emissive, so we override
## each surface at load. Purely cosmetic; skipped for any non-standard material.
func _apply_glow() -> void:
	for node in _character.find_children("*", "MeshInstance3D", true, false):
		var mi := node as MeshInstance3D
		var mat := mi.get_active_material(0) as StandardMaterial3D
		if mat == null:
			continue
		var m := mat.duplicate() as StandardMaterial3D
		var is_eye: bool = mi.name.to_lower().begins_with("eye")
		m.emission_enabled = true
		m.emission = Color(0.85, 1.0, 0.35) if is_eye else m.albedo_color
		m.emission_energy_multiplier = 6.0 if is_eye else 0.28
		mi.set_surface_override_material(0, m)


## Sets how urgently the shamble plays, from [param closing] (0 = holding steady,
## 1 = gaining fast). No-op while a lunge is playing.
func set_urgency(closing: float) -> void:
	if _anim == null or _lunging:
		return
	_anim.speed_scale = lerpf(SHAMBLE_MIN, SHAMBLE_MAX, clampf(closing, 0.0, 1.0))


## Fires the one-shot grab when the zombie catches the player.
func lunge() -> void:
	if _anim == null or _lunging or not _clips.has(CLIP_LUNGE):
		return
	_lunging = true
	_anim.speed_scale = 1.0
	_anim.play(CLIP_LUNGE, 0.1)


## Returns from a lunge to the shamble. The intro cinematic reuses the grab as a
## jump-scare at the camera, so it needs a way to hand a working pursuer back to
## gameplay afterwards (a gameplay lunge ends the run, so it never comes back).
func recover() -> void:
	if _anim == null:
		return
	_lunging = false
	_anim.speed_scale = 1.0
	if _clips.has(CLIP_SHAMBLE):
		_anim.play(CLIP_SHAMBLE, 0.2)
